# Core Colors
background            #161217
foreground            #eae0e7
selection_foreground  #e6b6f2
selection_background  #452152
cursor                #e6b6f2
cursor_text_color     #161217

# Regular Colors
color0  #161217
color1  #ffb4ab
color2  #e6b6f2
color3  #f5b7b3
color4  #f9d8ff
color5  #f2dcf3
color6  #d5c0d7
color7  #eae0e7

# Bright Colors
color8  #3d373d
color9  #ffb4ab
color10 #e6b6f2
color11 #f5b7b3
color12 #f9d8ff
color13 #f2dcf3 
color14 #d5c0d7
color15 #eae0e7
