# Multimedia video
windowrulev = tag +multimedia_video, class:^(mpv)$
windowrulev = tag +multimedia_video, class:^(Mpv)$
windowrulev = tag +multimedia_video, class:^(vlc)$

# Settings apps
windowrulev = tag +settings, class:^(nm-applet)$
windowrulev = tag +settings, class:^(nm-connection-editor)$
windowrulev = tag +settings, class:^(blueman-manager)$
windowrulev = tag +settings, class:^(org.gnome.FileRoller)$
windowrulev = tag +settings, class:^(org.gnome.DiskUtility)$
windowrulev = tag +settings, class:^(wihotspot)$
windowrulev = tag +settings, class:^(wihotspot-gui)$

# Viewer apps
windowrulev = tag +viewer, class:^(org.gnome.SystemMonitor)$
windowrulev = tag +viewer, class:^(org.gnome.Evince)$
windowrulev = tag +viewer, class:^(eog)$
windowrulev = tag +viewer, class:^(org.gnome.Loupe)$