# APPLIACTIONS BLUR
windowrulev = noblur, tag:multimedia_video
windowrulev = opacity 1.0, tag:multimedia_video
windowrulev = opacity 0.8, tag:settings
windowrulev = opacity 0.8, class:^(org.gnome.Nautilus)$
windowrulev = opacity 0.9, class:^(gedit|org.gnome.TextEditor|mousepad)$
windowrulev = opacity 0.9, class:^(org.pulseaudio.pavucontrol)$
windowrulev = opacity 0.9, class:^(kitty)$
windowrulev = opacity 0.85 override 0.7 override 1 override, class:^(discord|vesktop|org.telegram.desktop)$
windowrulev = opacity 0.8 override 0.6 override 1 override, class:^(Spotify)$
windowrulev = opacity 0.9 override 0.7 override 1 override, class:^(zen)$
#windowrulev = opacity 0.8 override 0.6 override 1 override, tag:viewer

# LAYER RULES
#layerrule = blur, rofi
#layerrule = ignorezero, rofi
#layerrule = ignorealpha 0.5, rofi
#layerrule = dimaround, rofi
#layerrule = animation popin 10%, rofi
#layerrule = blur, notifications
#layerrule = ignorezero, notifications
layerule = blur, waybar
#layerrule = ignorezero, waybar
layerule = ignorealpha 0.5, waybar
layerule = ignorealpha 0.5, tag:notif*
layerule = blur, logout_dialog

# SWAYNC BLUR & XRAY
layerule = blur, swaync-control-center
layerule = blur, swaync-notification-window
layerule = ignorezero, swaync-control-center
layerule = ignorezero, swaync-notification-window
layerule = ignorealpha 0.5, swaync-control-center
layerule = ignorealpha 0.5, swaync-notification-window
layerule = xray 0, swaync-control-center
layerule = xray 0, swaync-notification-window

#FLOAT
windowrulev = float, tag:settings
windowrulev = float, tag:viewer
windowrulev = float, tag:multimedia_video
windowrulev = size 900 506, tag:multimedia_video
windowrulev = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev = size 50% 60%, class:^(org.pulseaudio.pavucontrol)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# POP UPS AND DIALOGUES
windowrulev = float, title:^(Save As|Save a File|Pick Files)$
windowrulev = size 50% 60%, title:^(Save As|Save a File|Pick Files)$
windowrulev = center, title:^(Save As|Save a File|Pick Files)$
windowrulev = float, initialTitle:(Open Files)
windowrulev = size 70% 60%, initialTitle:(Open Files)
windowrulev = float, title:^(wiremix)$
windowrulev = size 700 300, title:^(wiremix)$
windowrulev = move 100%-739 50, title:^(wiremix)$
windowrulev = stayfocused, title:^(wiremix)$